use_frameworks!

target 'KNVUNDNumberPadInputHelper_Example' do
  pod 'KNVUNDNumberPadInputHelper', :path => '../'

  target 'KNVUNDNumberPadInputHelper_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
